services:
  - type: web
    name: tryhard-bot
    env: python
    plan: free                    
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    environment:
      pythonVersion: 3.12.5

